### ISSUE TITLE
Faculdade vs. Curso - o que te torna um senior?

### ISSUE THREAD

**Issue by erycsilva** [tchaguitos/tretadev#4]
Fiquei sabendo que alguns cursos te tornam senior em 2 meses, enquanto a faculdade forma juniors em 4 anos. Deixo a pergunta pra vocês: senior existe?

**To-do:**

- [ ] Responder a pergunta: Senior existe?

**Comment by tchaguitos** [comment]
eu ouvi uma galera dizer que só o curso bastante. dizem que faculdade é só perda de tempo

**Comment by tchaguitos** [comment]
eu ouvi uma galera dizer que só o curso basta. dizem que faculdade é só perda de tempo

**Comment by mateusavila** [comment]
A questão é que é claro definirmos o papel de junior pra pleno, que envolve a entrega parcial ou total de um projeto. Ser sênior envolve questões de domínio mais amplo, discussão acerca de regras de negócios, posicionamento acerca de questões técnicas que podem envolver muito dinheiro na jogada. O Sênior tem maior responsabilidade técnica.

**Comment by erycsilva** [comment]
Mateus Avila ganhou a treta dev
