### ISSUE TITLE
Angular, React ou VueJS?

### ISSUE THREAD

**Issue by Joaovsa7** [tchaguitos/tretadev#6]
🤔

**Comment by erycsilva** [comment]
não deu nem tempo hahahaha

**Comment by jmurowaniecki** [comment]
> não deu nem tempo hahahaha

Pior… Não deu.

Mas nesse meio tempo surgiram outros 4 frameworks, 8 libs e 15 piadas novas a respeito 😆

**Comment by jmurowaniecki** [comment]
Falando sério agora.

Tive boas experiências com Vue e excelentes com Angular - o que me levou a adotar ele como meu framework principal pra front por anos.

Recentemente tive uma imersão em React no produto de um cliente, e o projeto todo foi relativamente bem construído, tem storybooks bem feitos, 60%+ dos cases testados, relativamente baixa complexidade geral e manutenibilidade A- (segundo as métricas próprias definidas pelo time - então né, vai saber).

Todavia tem se mostrado uma ferramenta incrível e tenho optado por usar React nos meus testes, labs e projetos paralelos e tenho obtido um sucesso similar ao que vinha obtendo com Angular.

Se eu fosse criar uma tabela do que tenho passado recentemente seria algo tipo

Questão | VueJS | Angular.io | React
-------------|----------|----------------|---------
Rapidez na criação de novo projeto (auth, forms, dashboards, páginas, etc)| 4 - Demoro pra customizar | 5 - Vai rapidinho | 3 - Ainda tem umas curvas de aprendizagem dependendo das necessidades dos componentes.
Rapidez na implementação de novas features | 4 - Dependendo da complexidade pode ser que perca um pouco de tempo pesquisando | 5 - Geralmente vai tranquilo | 3 - Tem uma curva considerável de aprendizagem.
Tempo geral entre build e deploy | 3 - Não chega a ser terrível, os tamanhos dos artefatos são razoáveis e os rebuilds sao relativamente inteligentes | 2 - Mesmo com boas práticas o build tende a ser o mais demorado, eventualmente necessita alguma intervenção manual ou customização mais profunda entre ambientes | 4 - Tem se mostrado rápido em ambos os sentidos: tanto build quanto deploy. Os pipelines (apesar de similares) tendem a fluir com maior agilidade entre os estados e pouca (ou nenhuma - que eu lembre) customização entre ambientes foi necessária (até agora pelo que tenho testado).
Typescript, Code quality, lint, testes | 3 - É bem doloroso implementar TS em um projeto que tenha iniciado em JS. Gera um gargalo de processamento das dependências, retrabalho tanto na configuração do projeto quanto em componentes que se comunicarão com os novos. Aumenta consideravelmente o tempo de processamento das builds. | 3 - De forma geral a maleta vem pronta nesse sentido. Apesar de pesada e lenta, funciona bem. | 4 - É bastante customizável em todos os sentidos. Ainda tá me ganhando pelo processamento dos pipelines ser mais veloz e eficiente.
> Fonte dos dados dessa tabela: minha cabeça.


A real é que eu gosto desses três.

Até pouco mais de um mês atrás eu tinha o Angular.io encabeçando minha lista de favoritos, agora tô em dúvida entre ele e React.
